name: wf-develop-pr
on:
  pull_request:
    branches:
      -develop
jobs:
  develop-pr-jib:
    rul=ns-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Lint HTML and CSS
        run: |
          npx htmlhint "**/*.html"
          npx stylelint "**/*.css"
      - name: Build Website
        run: npx parcel build "./src/index.html" --dist-dir "./dev" --public-url "./"
